#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

BUILD_CONFIG_PATH="${ROOT_DIR}/.build-config"

PROJECT_FLAGS=(
  "libelaracore"
  "libelaradebug"
  "libelarathreads"
  "libelaraencryption"
  "libelaraevent"
  "libelaraformat"
  "libelaraio"
  "libelaradata"
  "libelarasockets"
  "libelarauirpc"
  "libelarapythonthreads"
  "libelaraparallelassembly"
  "libelaraserializer"
  "libelaravector"
  "libelaraui"
  "elaraunittests"
  "elaraprojectbuilder"
  "elaracpplint"
)

FEATURE_FLAGS=(
  "mysql"
  "sqlite"
  "xml"
)

BUILD_PROFILES=(
  "release"
  "debug"
  "asan"
)

bool_to_text() {
  if [[ "${1:-}" == "yes" ]]; then
    printf 'yes\n'
  else
    printf 'no\n'
  fi
}

valid_profile() {
  local profile="${1:-}"
  local candidate

  for candidate in "${BUILD_PROFILES[@]}"; do
    if [[ "$candidate" == "$profile" ]]; then
      return 0
    fi
  done

  return 1
}

load_build_config() {
  if [[ ! -f "$BUILD_CONFIG_PATH" ]]; then
    return 1
  fi

  # shellcheck disable=SC1090
  source "$BUILD_CONFIG_PATH"

  if [[ -z "${PROJECT_libelaraparallelassembly:-}" && -n "${PROJECT_elaraparallelassembly:-}" ]]; then
    PROJECT_libelaraparallelassembly="$PROJECT_elaraparallelassembly"
  fi
  return 0
}

save_build_config() {
  local profile="$1"
  local flag=""

  {
    printf '# Generated by ./build.sh\n'
    for flag in "${PROJECT_FLAGS[@]}"; do
      printf 'PROJECT_%s=%s\n' "$flag" "$(bool_to_text "${!flag:-yes}")"
    done
    for flag in "${FEATURE_FLAGS[@]}"; do
      printf 'FEATURE_%s=%s\n' "$flag" "$(bool_to_text "${!flag:-yes}")"
    done
    printf 'BUILD_PROFILE=%s\n' "$profile"
  } > "$BUILD_CONFIG_PATH"
}

prompt_yes_no() {
  local prompt="$1"
  local reply

  while true; do
    read -r -p "$prompt [Y/n] " reply
    reply="${reply:-y}"
    case "$reply" in
      [Yy]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo]) return 1 ;;
      *) echo "Please answer y or n." ;;
    esac
  done
}

run_interactive() {
  local -a configure_args=()
  local flag
  local profile="release"
  local saved_project_var=""
  local saved_feature_var=""

  if load_build_config; then
    echo "Loading build options from ${BUILD_CONFIG_PATH}."

    for flag in "${PROJECT_FLAGS[@]}"; do
      saved_project_var="PROJECT_${flag}"
      if [[ "${!saved_project_var:-yes}" != "yes" ]]; then
        configure_args+=("--disable-${flag}")
      fi
    done

    for flag in "${FEATURE_FLAGS[@]}"; do
      saved_feature_var="FEATURE_${flag}"
      if [[ "${!saved_feature_var:-yes}" != "yes" ]]; then
        configure_args+=("--disable-${flag}")
      fi
    done

    if valid_profile "${BUILD_PROFILE:-}"; then
      profile="$BUILD_PROFILE"
    fi
  else
    echo "Select build options."

    for flag in "${PROJECT_FLAGS[@]}"; do
      if prompt_yes_no "Build ${flag}?"; then
        printf -v "$flag" 'yes'
      else
        printf -v "$flag" 'no'
        configure_args+=("--disable-${flag}")
      fi
    done

    for flag in "${FEATURE_FLAGS[@]}"; do
      if prompt_yes_no "Enable ${flag}?"; then
        printf -v "$flag" 'yes'
      else
        printf -v "$flag" 'no'
        configure_args+=("--disable-${flag}")
      fi
    done

    echo
    echo "Choose build profile."
    echo "  1. release - fast optimized build"
    echo "  2. debug   - debug symbols, easier debugging"
    echo "  3. asan    - AddressSanitizer + UndefinedBehaviorSanitizer"
    select profile in "${BUILD_PROFILES[@]}"; do
      if [[ -n "${profile:-}" ]]; then
        break
      fi
      echo "Please choose a valid profile number."
    done

    save_build_config "$profile"
  fi

  echo
  echo "Running autoreconf..."
  autoreconf -fi

  echo "Running configure..."
  if ((${#configure_args[@]} > 0)); then
    ./configure "${configure_args[@]}"
  else
    ./configure
  fi

  echo "Running make..."
  make BUILD_PROFILE="$profile"
}

run_matrix() {
  local -a all_flags=("${PROJECT_FLAGS[@]}" "${FEATURE_FLAGS[@]}")
  local total_flags=${#all_flags[@]}
  local total_combinations=$((1 << total_flags))
  local mask
  local i
  local -a args

  autoreconf -fi

  for ((mask = 0; mask < total_combinations; mask++)); do
    args=()
    for ((i = 0; i < total_flags; i++)); do
      if (( (mask & (1 << i)) == 0 )); then
        args+=("--disable-${all_flags[i]}")
      fi
    done

    printf '\n[%d/%d] ./configure' "$((mask + 1))" "$total_combinations"
    if ((${#args[@]} > 0)); then
      printf ' %s' "${args[@]}"
    fi
    printf '\n'

    if ! ./configure "${args[@]}"; then
      echo "Skipping make: configure rejected this combination"
      continue
    fi

    make remove >/dev/null 2>&1 || true
    make clean >/dev/null 2>&1 || true
    make
  done

  ./configure
}

run_smoke() {
  echo "Running framework smoke validation..."
  autoreconf -fi
  ./configure
  make smoke BUILD_PROFILE="${BUILD_PROFILE:-release}"
}

case "${1:-interactive}" in
  interactive)
    run_interactive
    ;;
  --matrix)
    run_matrix
    ;;
  --smoke)
    run_smoke
    ;;
  *)
    echo "Usage: $0 [interactive|--matrix|--smoke]" >&2
    exit 1
    ;;
esac
